version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-app
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - MONGO_URI=mongodb://mono:27017
      - MONGO_DB=urlshortener
      - SERVER_ADDRESS=:8080
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - urlshortener-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  mongo:
    image: mongo:latest
    container_name: urlshortener-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=urlshortener
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - urlshortener-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  mongo-express:
    image: mongo-express:latest
    container_name: urlshortener-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - urlshortener-network
    restart: unless-stopped

volumes:
  mongodb_data:
    name: urlshortener-mongodb-data
  mongodb_config:
    name: urlshortener-mongodb-config

networks:
  urlshortener-network:
    name: urlshortener-network
    driver: bridge